### ISSUE TITLE
Questions about history of rails and background on community leaders do not reflect candidate's ability to code

### ISSUE THREAD

**Issue by eford1** [afeld/rails_interview_questions#6]
What is "community awareness and resourcefulness" and why is it important? Are there other ways to test the root of this besides these kinds of questions?

I am also concerned that having deep knowledge of certain community leaders could actually convey dogmatic tendencies. You don't want to hire someone who makes decisions based on, "well, that's what x person said" instead of understanding and weighing the technical implications.

**Comment by afeld** [comment]
> What is "community awareness and resourcefulness" and why is it important?

Hmm, that's a big question. I do believe that it _is_ important, but need to think a bit on the "why".

> Are there other ways to test the root of this besides these kinds of questions?

Surely. I'm open to ideas :wink: 

> I am also concerned that having deep knowledge of certain community leaders could actually convey dogmatic tendencies.

I think there's a line between "knowledge of" and "_deep_ knowledge of...I changed the only question that I felt went overboard in #7. If I was interviewing someone and they didn't know the three other names that are listed, I would question how much time they had spent in the Rails community. That knowledge is certainly a litmus test rather than being something directly useful, but am open to ideas about other ways to go about it.

**Comment by davidcelis** [comment]
I disagree that involvement in the Ruby/Rails community is important for nabbing a job as a developer. Man proficient coders hold hobbies outside of the tech industry or are otherwise too busy to keep up to date with "community leaders." These folks should be penalized for doing things they enjoy outside of work that don't involve Rails?

**Comment by jessieay** [comment]
I personally wouldn't ask people about DHH or Matz or Tenderlove because that feels insider-y to me. I happen to know who those people are, but I don't think it makes me any better at what I do.

I *would* want to ask interviewees what about their favorite programming-related blogs / books / podcasts / screencasts, since having preferred resources shows a thirst for learning, which is an important attribute of anyone I'd want to hire. The answer to that question might be enlightening to the interviewer. too!

**Comment by davidcelis** [comment]
Put another way: if I were interviewing for a job as a person who writes vending machine software, how much would you expect me to know about the creator(s) of the vending machine?

**Comment by davidcelis** [comment]
> I would want to ask interviewees what about their favorite programming-related blogs / books / podcasts / screencasts, since having preferred resources shows a thirst for learning, which is an important attribute of anyone I'd want to hire. The answer to that question might be enlightening to the interviewer, too!

@jessieay I actually think that this is a bit dangerous too. It's rarer than you think for developers to be afforded the privilege of learning on the job. Reading programming-related blogs or books, listening to developer podcasts, watching screencasts… These are all things that I'd consider a luxury for those who either A) are given some time on the job to learn or B) give up on other hobbies that they find may find important

**Comment by pkarman** [comment]
I feel confident I would fail more than half of these questions, including (and especially) the community questions. Take that for what its worth.

**Comment by afeld** [comment]
@pkarman Curious to hear about the technical questions you don't think you'd get, and what you would ask instead. Game to open a separate issue?

**Comment by ccostino** [comment]
I share @pkarman's sentiments about a solid chunk of these questions and would also be happy to engage in a separate conversation about that.

Regarding the community questions and reading outside blogs, I think you raise an excellent point, @davidcelis, about such things being a luxury and is something I'd be afraid of as well.  This is something I'm especially keen on right now as my time outside of work is at an absolute premium due to having a baby at home.  In short, when I'm not at work, I'm not spending time programming all that much or doing anything related to the computer for that matter.  I'm spending it with my family or just resting due to sheer exhaustion!

I completely agree with you @jessieay about wanting to hire actively engaged folks who have a thirst for learning, and that such a question can lead to an edifying discussion for all parties involved with the interview!  However, I would also exercise caution in placing too much weight on it.  Perhaps the person interviewing doesn't have the means to get deeply involved with anything outside of work and their current job doesn't afford them the opportunity to learn more and develop their skills further either, hence the reason they are seeking something new to begin with; they would like to be a part of something far more fulfilling that they feel they can both contribute to and learn from as well (as was very much the case for me recently).

**Comment by afeld** [comment]
Closed by #7.
